services:
  product-service:
    image: product-service:local
    container_name: product-service
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    environment:
      NODE_ENV: production
      PORT: ${PRODUCT_PORT_CONTAINER}
    ports:
      - "${PRODUCT_PORT_HOST}:${PRODUCT_PORT_CONTAINER}"
    restart: unless-stopped